name: marketplace-api-dev
services:
  products-api:
    image: products-api-dev
    build:
      context: .
      dockerfile: ProductsApi/Dockerfile
      args:
        BUILD_CONFIGURATION: Debug
    environment:
      ASPNETCORE_ENVIRONMENT: Development

    ports:
      - "6032:8080"
