name: marketplace-api
services:
  goods-api:
    image: goods-api
    build:
      context: .
      dockerfile: GoodsApi/Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    environment:
      ASPNETCORE_ENVIRONMENT: Production
          
    ports:
      - "5032:8080"
