name: marketplace-api
services:
  products-api:
    image: products-api
    build:
      context: .
      dockerfile: ProductsApi/Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    environment:
      ASPNETCORE_ENVIRONMENT: Production
          
    ports:
      - "5032:8080"
