events {}

http {
    upstream products_api {
        server products-api:8080;
    }
    
    upstream purchases_api {
        server purchases-api:8080;
    }
    
    upstream users_api {
        server users-api:8080;
    }
    
    server {
        listen 80;
        
        location /api/products {
            proxy_pass http://products_api;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Cookie $http_cookie;
            proxy_pass_header Set-Cookie;
        }
        
        location /swagger/products/ {
            proxy_pass http://products_api/swagger/;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Cookie $http_cookie;
            proxy_pass_header Set-Cookie;
        }
        
        location /api/purchases {
            proxy_pass http://purchases_api;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Cookie $http_cookie;
            proxy_pass_header Set-Cookie;
        }
        
        location /swagger/purchases/ {
            proxy_pass http://purchases_api/swagger/;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Cookie $http_cookie;
            proxy_pass_header Set-Cookie;
        }
        
        location /api/users {
            proxy_pass http://users_api;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Cookie $http_cookie;
            proxy_pass_header Set-Cookie;
        }
        
        location /swagger/users/ {
            proxy_pass http://users_api/swagger/;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Cookie $http_cookie;
            proxy_pass_header Set-Cookie;
        }
    }
}